# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='Film', to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='Film', to='movies.Genre'),
        ),
    ]
